/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClockFoxIndexRouteImport } from './routes/clock/fox/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockFoxIndexRoute = ClockFoxIndexRouteImport.update({
  id: '/clock/fox/',
  path: '/clock/fox/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clock/fox': typeof ClockFoxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clock/fox': typeof ClockFoxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clock/fox/': typeof ClockFoxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clock/fox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clock/fox'
  id: '__root__' | '/' | '/clock/fox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClockFoxIndexRoute: typeof ClockFoxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock/fox/': {
      id: '/clock/fox/'
      path: '/clock/fox'
      fullPath: '/clock/fox'
      preLoaderRoute: typeof ClockFoxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClockFoxIndexRoute: ClockFoxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
